version: '3.8'
services:
  simple-fe:
    environment:
      - HLS_HOST=localhost
      - HLS_PORT=9888
      - MQTT_HOST=localhost
      - MQTT_WS_PORT=8000
    ports:
      - "3003:3003"
    profiles:
      - dev
